# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # 04240b32048afcb9d3c07b623f499789c2799dca6d21c671ba3b0e17f6807a7e2a6384ec9686365967b62d829955df5a39b95468121215900626056de90e31e2
  secret_key_base: 033cab8963a75edb62f60d2709519da4af9c6ea3f4719e40c7b03dd828baa5f271ae711da19e01670c924aaba072a1f56671262e4339316a479493de75da4066

test:
  secret_key_base: 7ad0ded6f49c857ccca0a36dc113c9674abeb1b727838870338df615abdacca558d6e380a6963bf17a3842738227dca9d0e9e688f28d91fb995880ca723a31f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
